outlays/users/blueprints.py
# -*- coding: utf-8 -*-
__author__ = 'winzo'


from flask import Blueprint, flash, request, redirect, url_for, g, render_template, current_app
from .form.signup import SignupForm
from .form.login import LoginForm
from .form.reset_password import ResetPasswordForm
from .form.activation_code import ActivationCodeForm
from .user import UserManager, User
from .models import User as UserModel
from flask.ext.mail import Message

from outlays.emails import mail


blueprint = Blueprint('users', __name__, template_folder='templates', static_folder='static')
user_manager = UserManager()


@blueprint.before_app_request
def load_user():
    g.user = User()


@blueprint.teardown_app_request
def save_user(response):
    g.user.save()
    return response


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    next_url = request.args.get('next') or url_for('index')

    if g.user.is_authorized():
        return redirect('/' + next_url)

    form = LoginForm(request.form, csrf_enabled=False)
    if request.method == 'POST' and form.validate():

        user = g.session.query(UserModel)\
            .filter(UserModel.email == form.email.data)\
            .filter(UserModel.password == g.user.hash_it(form.password.data))\
            .first()

        if user:
            g.user.login(user)
            flash(u'You signed in as %s' % (g.user.name), 'success')
            return redirect('/' + next_url)

        flash(u'Invalid email and/or password', 'danger')

    if request.method == 'POST' and not form.validate():
        flash(u'Log in failed. See errors in form', 'danger')

    return render_template('users/login.html', form=form)


@blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    next_url = request.args.get('next') or url_for('index')

    if g.user.is_authorized():
        return redirect('/' + next_url)

    form = SignupForm(request.form, csrf_enabled=False)
    if request.method == 'POST' and form.validate():

        user = UserModel()
        user.name = form.name.data
        user.email = form.email.data
        user.phone = form.phone.data

        user.password = g.user.hash_it(form.password.data)

        g.session.add(user)
        g.session.commit()

        g.user.login(user)

        flash(u'You signed in as %s' % (g.user.name), 'success')
        return redirect('/' + next_url)

    if request.method == 'POST' and not form.validate():
        flash(u'Signup failed. See errors in form', 'danger')

    return render_template('users/signup.html', form=form)


@blueprint.route('/logout', methods=['GET'])
def logout():
    g.user.logout()
    return redirect(url_for('index'))


@blueprint.route('/reset_password', methods=['GET', 'POST'])
def activation_code():
    if g.user.is_authorized():
        return redirect(url_for('index'))

    form = ActivationCodeForm(request.form, csrf_enabled=False)

    if request.method == 'POST' and form.validate():
        user = g.session.query(UserModel).filter(UserModel.email == form.email.data).first()

        if not user:
            flash(u'User does not exists', 'danger')
            return render_template('users/activation_code.html', form=form)

        user.gen_activation_code()
        g.session.commit()

        # send message
        msg = Message('[Epic Outlays] Password reset', recipients=[user.email], sender=current_app.config['DEFAULT_MAIL_SENDER'])
        msg.body = request.host_url[:-1] + url_for('.reset_password', code=user.activation_code)
        msg.html = '<a href="' + request.host_url[:-1] + url_for('.reset_password', code=user.activation_code) + '">Click</a> to set your new password'

        # HACK: mail.send(msg) should work but not
        with mail.connect() as conn:
            connection = conn.configure_host()
            connection.sendmail(current_app.config['DEFAULT_MAIL_SENDER'], user.email, msg.as_string())

        flash(u'Email with activation code sent', 'success')
        return redirect(url_for('index'))

    if request.method == 'POST' and not form.validate():
        flash(u'Enter a valid email', 'danger')

    return render_template('users/activation_code.html', form=form)


@blueprint.route('/reset_password/<code>', methods=['GET', 'POST'])
def reset_password(code):
    if g.user.is_authorized():
        return redirect(url_for('index'))

    user = g.session.query(UserModel)\
        .filter(UserModel.activation_code == code)\
        .first()

    if not user:
        return render_template('users/invalid_activation_code.html')

    form = ResetPasswordForm(request.form, csrf_enabled=False)

    if request.method == 'POST' and form.validate():
        if user.email == form.email.data:
            user.activation_code = None
            user.password = g.user.hash_it(form.password.data)

            g.session.commit()

            flash(u'Your password changed', 'success')

            g.user.login(user)
            return redirect(url_for('index'))
        else:
            flash(u'Enter a valid email', 'danger')

    if request.method == 'POST' and not form.validate():
        flash(u'Enter a valid data', 'danger')

    return render_template('users/reset_password.html', form=form)

outlays/templates/index.html
<!doctype html>
<html lang="en">

<head>
  <title>Epic Outlays</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="Description" content="Epic Outlays">

  <link async href="/static/dist/vendors~main.css" rel="stylesheet">
</head>

<body>
  <link href="/static/dist/main.css" rel="stylesheet" />
  <div id="root" class="site-wrapper"></div>
  <footer class='blog-footer'>
    <div class='container'>
      Powered by <a href='mailto:outlays@efstudios.org'>EpicFail Studios</a>.
    </div>
  </footer>

  <script>
    window.eo = {
      currentUser: {{ user | safe }},
      deposit_types: {{ deposit_types | safe }},
      deposits: {{ deposits | safe }},
      currencies: {{ currencies | safe }},
      transactions: [],
  }
  </script>
  <script async src="/static/dist/vendors~main.chunk.js"></script>
  <script async src="/static/dist/main.js"></script>
  <!-- <script async src="/dist/styles.chunk.js"></script> -->
</body>

</html>

outlays/templates/index.old.html
{% extends "layout.html" %}

{% block title %}Transactions{% endblock %}
{% block description %}Your all transactions on all debits{% endblock %}

{% block header %}
<link href="{{ url_for('static', filename='lib/select2-3.4.8/select2.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav js-nav js-hidden">
      <a class="blog-nav-item js-nav-item" href="#transactions"><span
          class="glyphicon glyphicon-list visible-xs"></span><span class="hidden-xs">Transactions</span></a>
      <a class="blog-nav-item js-nav-item" href="#deposits"><span
          class="glyphicon glyphicon-briefcase visible-xs"></span><span class="hidden-xs">Deposits</span></a>
      <a class="blog-nav-item js-nav-item" href="#currencies"><span
          class="glyphicon glyphicon-euro visible-xs"></span><span class="hidden-xs">Currencies</span></a>
      {% if g.user.is_authorized() %}
      <a class="blog-nav-item js-nav-item pull-right" href="{{ url_for('users.logout') }}"><span
          class="glyphicon glyphicon-log-out visible-xs"></span><span class="hidden-xs">Logout</span></a>
      <span class="blog-nav-text pull-right">{{ g.user.name }}</span>
      {% else %}
      <a class="blog-nav-item pull-right" href="{{ url_for('users.login') }}"><span
          class="glyphicon glyphicon-log-in visible-xs"></span><span class="hidden-xs">Login</span></a>
      {% endif %}
    </nav>
  </div>
</div>
<script type="text/javascript">
  $(window).ready(function () {
    window.menu = new OutlaysMenu({
      el: $('.js-nav')[0]
    });
  });
</script>

<div class="container">

  <div class="blog-header js-header js-hidden">
    <h1 class="blog-title js-title">{{ self.title() or '&nbsp;' }}</h1>
    <p class="blog-description js-description">{{ self.description() or '&nbsp;' }}</p>
  </div>
  <script type="text/javascript">
    $(window).ready(function () {
      window.header = new OutlaysHeader({
        el: $('.js-header')[0]
      });
    });
  </script>

  <div class="row">

    <div class="col-sm-12 blog-main">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

      <div class="blog-body js-body"></div>

      <script src="{{ url_for('static', filename='lib/backbone.paginator-2.0/backbone.paginator.min.js') }}"></script>

      {% include "js/simple_list.html" %}
      {% include "transactions/form.html" %}
      {% include "transactions/list.html" %}
      {% include "deposits/form.html" %}
      {% include "deposits/list.html" %}

      <script src="{{ url_for('static', filename='js/deposit_types/model.js') }}"></script>
      <script src="{{ url_for('static', filename='js/deposit_types/collection.js') }}"></script>
      <script src="{{ url_for('static', filename='js/currencies/model.js') }}"></script>
      <script src="{{ url_for('static', filename='js/currencies/collection.js') }}"></script>
      <script src="{{ url_for('static', filename='js/deposits/model.js') }}"></script>
      <script src="{{ url_for('static', filename='js/deposits/collection.js') }}"></script>
      <script src="{{ url_for('static', filename='js/deposits/form.js') }}"></script>
      <script src="{{ url_for('static', filename='js/deposits/list.js') }}"></script>
      <script src="{{ url_for('static', filename='js/transactions/model.js') }}"></script>
      <script src="{{ url_for('static', filename='js/transactions/collection.js') }}"></script>
      <script src="{{ url_for('static', filename='js/transactions/form.js') }}"></script>
      <script src="{{ url_for('static', filename='js/transactions/list.js') }}"></script>
      <script src="{{ url_for('static', filename='js/view/simple_list.js') }}"></script>


      <script src="{{ url_for('static', filename='js/router.js') }}"></script>


      <script src="{{ url_for('static', filename='lib/select2-3.4.8/select2.min.js') }}"></script>

      <script type="text/javascript">
        $(window).ready(function () {

          window.collections = {
	    currencies: new CurrencyCollection({{ currencies| safe }}),
            deposits: new DepositCollection({{ deposits| safe }})
          };
          var router = new Router();
        });
      </script>
    </div><!-- /.blog-main -->

    <!-- <div class="col-sm-3 blog-sidebar">

            <ul class="list-group">
              <li class="list-group-item">
                <span class="pull-right">R <span class="sum label label-success">13000</span></span> Cash
              </li>
              <li class="list-group-item">
               <span class="pull-right">R <span class="sum label label-danger">-2000</span></span> Mastercard
              </li>
              <li class="list-group-item">
                <span class="pull-right">R <span class="sum label label-success">9000</span></span> Sberbank
              </li>
            </ul>

        </div> -->
    <!-- /.blog-sidebar -->

  </div><!-- /.row -->

</div><!-- /.container -->
{% endblock %}

outlays/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %} - Epic Outlays</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link rel="shortcut icon" href="/static/favicon.png" />
    <link href="{{ url_for('static', filename='lib/bootstrap-3.1.1/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/layout.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='lib/bootstrap-datetimepicker-2.1.30/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/overrides.css') }}" rel="stylesheet" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='lib/bootstrap-3.1.1/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/underscore-1.6.0/underscore-min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/moment-2.6.0/js/moment-with-langs.min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/backbone-1.1.2/backbone-min.js') }}"></script>
    <script src="{{ url_for('static', filename='lib/bootstrap-datetimepicker-2.1.30/js/bootstrap-datetimepicker.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/outlays.js') }}"></script>
    <script src="{{ url_for('static', filename='js/menu.js') }}"></script>
    <script src="{{ url_for('static', filename='js/header.js') }}"></script>

    {% block header %}{% endblock %}
</head>
<body>
    <div class="site-wrapper">
        {% block body %}{% endblock %}
    </div>
    <div class="blog-footer">
        <div class="container">
            Powered by <a href="mailto:outlays@efstudios.org">EpicFail Studios</a>.
        </div>
    </div>
</body>
</html>